export const catalog = [
  // 12 terrain and landscape pieces
  ['tile','地块','terrain','⬡','#55c7a7','tile'],
  ['sand','沙地','terrain','▰','#eabf85','ground'],
  ['pond','池塘','terrain','◉','#70d2df','pond'],
  ['hill','草丘','terrain','▲','#79c397','hill'],
  ['mountain','雪山','terrain','⛰','#9da7bd','mountain'],
  ['rocks','岩石群','terrain','◆','#8796a9','rocks'],
  ['stream','溪流','terrain','〰','#72d2e6','stream'],
  ['path','石板路','terrain','▥','#cfb38c','path'],
  ['bridge','小桥','terrain','⌒','#c78660','bridge'],
  ['flowerfield','花田','terrain','✿','#e795a7','flowerfield'],
  ['cliff','悬崖','terrain','▨','#8c9c98','cliff'],
  ['islet','小岛','terrain','⬢','#5cc6a9','islet'],
  // 20 buildings
  ['cottage','蓝顶小屋','buildings','⌂','#6388cc','house'],
  ['redhouse','红顶小屋','buildings','⌂','#d97568','house'],
  ['farmhouse','农舍','buildings','⌂','#b89b67','house'],
  ['cabin','木屋','buildings','⌂','#8d765d','house'],
  ['barn','谷仓','buildings','▣','#bb6d64','barn'],
  ['windmill','风车','buildings','✳','#6688ba','windmill'],
  ['watermill','水车屋','buildings','◌','#8b71ab','watermill'],
  ['watchtower','瞭望塔','buildings','♜','#8e98b8','tower'],
  ['roundtower','圆塔','buildings','♜','#8577ae','tower'],
  ['castle','城堡','buildings','♜','#777fbe','castle'],
  ['gate','城门','buildings','⌑','#8b91a8','gate'],
  ['chapel','小礼堂','buildings','✧','#a07db5','chapel'],
  ['greenhouse','温室','buildings','▤','#7ebfc1','greenhouse'],
  ['market','集市棚','buildings','▥','#e79767','market'],
  ['bakery','面包房','buildings','⌂','#d89b71','bakery'],
  ['smithy','铁匠铺','buildings','⚒','#828d9d','smithy'],
  ['library','图书馆','buildings','▥','#9a86b6','library'],
  ['lighthouse','灯塔','buildings','♜','#d99377','lighthouse'],
  ['pagoda','宝塔','buildings','♜','#a55f62','pagoda'],
  ['observatory','观星台','buildings','◉','#8792c5','observatory'],
  // 18 plants
  ['pine','松树','plants','♠','#388f83','pine'],
  ['tallpine','高松','plants','♠','#327d77','pine'],
  ['fir','冷杉','plants','♠','#4b9b91','fir'],
  ['forest','小树林','plants','♠','#439982','forest'],
  ['oak','橡树','plants','♣','#67ad70','oak'],
  ['autumnoak','秋橡','plants','♣','#de9866','oak'],
  ['cherry','樱花树','plants','✿','#eaa1b3','cherry'],
  ['willow','垂柳','plants','♣','#8fbb69','willow'],
  ['palm','棕榈','plants','♣','#62b38a','palm'],
  ['bamboo','竹林','plants','╎','#77ab75','bamboo'],
  ['cypress','柏树','plants','♠','#477e6e','cypress'],
  ['bush','灌木','plants','●','#5caa86','bush'],
  ['hedge','树篱','plants','▬','#4e9e79','hedge'],
  ['flowers','花丛','plants','✿','#e790a4','flowers'],
  ['lavender','薰衣草','plants','✿','#a895ce','lavender'],
  ['mushrooms','蘑菇','plants','♧','#dc8a82','mushrooms'],
  ['cactus','仙人掌','plants','♣','#61a68a','cactus'],
  ['reeds','芦苇','plants','╎','#a1b779','reeds'],
  // 10 details
  ['bench','长椅','details','▰','#b88965','bench'],
  ['lantern','路灯','details','✦','#ecba79','lantern'],
  ['well','水井','details','◉','#8d9eb5','well'],
  ['fountain','喷泉','details','◉','#7abed4','fountain'],
  ['statue','雕像','details','♟','#b8b7b0','statue'],
  ['fence','木栅栏','details','╪','#b68d69','fence'],
  ['sign','路标','details','⚑','#c69568','sign'],
  ['cart','小推车','details','▰','#ba8b6e','cart'],
  ['campfire','篝火','details','✦','#e89a68','campfire'],
  ['dock','木码头','details','▰','#a88769','dock'],
].map(([id,name,category,glyph,color,shape])=>({id,name,category,glyph,color,shape}));

export const byId = Object.fromEntries(catalog.map(item=>[item.id,item]));
export const categories = [
  {id:'all',name:'全部',glyph:'✦'},
  {id:'terrain',name:'地形',glyph:'⬡'},
  {id:'buildings',name:'建筑',glyph:'⌂'},
  {id:'plants',name:'植物',glyph:'♣'},
  {id:'details',name:'装饰',glyph:'✧'},
];
