import {games,gameById,createState,act,tick,metrics,tasks,progress} from './games.js';
import {byId} from './catalog.js';
import {createWorld} from './world.js';
import {createMusic} from './music.js';
import {weatherOptions} from './weather.js';
const $=s=>document.querySelector(s);const id=new URLSearchParams(location.search).get('game')||'town',game=gameById[id]||games[0],store=`cloud-arcade-${game.id}-v1`;
let state=createState(game.id),tool=game.tools[0]?.[0]||'forest',paused=false,speed=1,last=performance.now(),time=0,resultShown=false,toastTimer;
try{const saved=JSON.parse(localStorage.getItem(store));if(saved?.version===1&&saved.id===game.id&&Array.isArray(saved.items)&&saved.items.length<40){state=saved;if(state.id==='train')state.running=null;if(state.id==='defense'&&state.battle){state.battle=false;state.wave--;state.enemies=[];state.shots=[];state.spawn=0;}}}catch{}
if(game.id==='puzzle')tool=state.hand[0];
document.title=`${game.name} · 云上游乐场`;$('#gameName').textContent=game.name;$('#gameEnglish').textContent=game.en;$('#gameNumber').textContent=game.n;$('#gameTag').textContent=game.tag;$('#caption').textContent=game.caption;$('#goal').textContent=game.goal;$('#guideTitle').textContent=game.name;$('#guideText').textContent=game.guide;$('#guideGoal').textContent=`目标：${game.goal}`;$('#toolTitle').textContent=game.id==='puzzle'?'本回合 · 三选一':'选择你的工具';
if(game.id==='train'){$('#destination').hidden=false;$('#legend').innerHTML='西侧：仓库 · 东侧：小镇<br>北侧：农场 · 山和池塘不可铺轨';}if(game.id==='garden')$('#legend').textContent='小苗 → 浇水 → 生长 → 收集花蜜';if(game.id==='defense')$('#legend').textContent='粉色小怪从西侧来 · 城堡在东侧';
function toast(m){$('#toast').textContent=m;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800);}
function save(){try{localStorage.setItem(store,JSON.stringify(state));}catch{}}
function operate(type,p={}){if(paused){toast('当前已暂停，点 Ⅱ 恢复后继续。');return;}const ok=act(state,type,p);toast(state.message);if(ok){sync();save();}else $('#message').textContent=state.message;}
const world=createWorld($('#viewport'),{id:game.id,onCell:p=>operate('place',{...p,tool}),onHover:(p,e,item)=>{const tip=$('#hoverTip');tip.hidden=!p;if(!p)return;const rect=$('#viewport').getBoundingClientRect();tip.style.left=`${Math.min(rect.width-170,e.clientX-rect.left+16)}px`;tip.style.top=`${Math.max(100,e.clientY-rect.top-25)}px`;let label=item?(byId[item.type]?.name||({rail:'铁轨',ballista:'重弩'})[item.type]):'空地';if(game.id==='garden'&&item?.age!==undefined)label+=item.collected?' · 已吸引访客':` · 生长 ${item.age}/${item.type==='cherry'?3:2}${item.wet?' · 已浇水':''}`;tip.textContent=`${label} · (${p.x}, ${p.z})`;}});
function tools(){const list=game.id==='puzzle'?state.hand.map(t=>[t,byId[t].name,'同类相邻 +6 · 异类相邻 +2']):game.tools;$('#tools').innerHTML='';for(const [t,name,desc]of list){const b=document.createElement('button');b.className='tool'+(tool===t?' active':'');b.dataset.tool=t;b.style.setProperty('--tool-color',byId[t]?.color||'#769989');const glyph=byId[t]?.glyph||({rail:'╪',erase:'⌫',water:'♧',harvest:'✦',ballista:'➶'})[t];b.innerHTML=`<span class="tool-icon">${glyph}</span><span><strong>${name}</strong><small>${desc}</small></span><span class="selected-dot">${tool===t?'●':''}</span>`;b.addEventListener('click',()=>{tool=t;tools();});$('#tools').append(b);}}
function sync(){world.rebuild(state);$('#metrics').innerHTML=metrics(state).map(([label,value])=>`<div class="metric"><small>${label}</small><strong>${value}</strong></div>`).join('');$('#tasks').innerHTML=tasks(state).map(([label,done])=>`<div class="task ${done?'done':''}"><i>${done?'✓':''}</i><span>${label}</span></div>`).join('');$('#progress').style.width=`${progress(state)*100}%`;$('#turn').textContent=game.id==='town'?`第 ${Math.min(20,state.turn)} / 20 天`:game.id==='puzzle'?`剩余 ${14-state.placed} 张`:game.id==='garden'?`${['春','夏','秋','冬'][Math.floor((state.turn-1)/4)%4]} · 第 ${state.turn} 天`:'';$('#message').textContent=state.message;const w=weatherOptions.find(w=>w.id===state.weather);$('#weather').textContent=`${w.icon} ${w.name}`;$('#weather').disabled=game.id==='garden';$('#weather').title=game.id==='garden'?'花园的天气随日期变化':'切换天气';$('#advance').hidden=!game.action;$('#advance').textContent=state.running?'火车正在行驶…':state.battle?`第 ${state.wave} 波进行中…`:game.action;$('#advance').disabled=!!state.running||!!state.battle||state.status!=='playing';document.querySelectorAll('[data-dest]').forEach(b=>{b.classList.toggle('active',b.dataset.dest===state.destination);b.disabled=!!state.running;});if(game.id==='puzzle'&&!state.hand.includes(tool))tool=state.hand[0];tools();if(state.status!=='playing'&&!resultShown){resultShown=true;setTimeout(()=>{if(state.status!=='playing')showResult();},600);}}
function showResult(){
 const won=state.status==='won';
 const titles={town:'小镇有了烟火气',puzzle:'拼出了一座好岛',train:'云上路线已通车',garden:'花园的小客人都来了',defense:'城堡守住了！'};
 const copies={
  town:()=>`${state.items.filter(i=>i.type==='cottage').length*2} 位居民在这里生活，仓库里还有 ${state.food} 份食物。`,
  puzzle:()=>`你用 14 块拼图拿到了 ${state.score} 分，完成 ${state.contracts.length} 个组合目标。`,
  train:()=>'小镇与农场各收到 4 箱货物，你搭出了自己的云上运输网。',
  garden:()=>'粉蝶、蜜蜂、小鸟和萤火虫，成为了这座花园的新邻居。',
  defense:()=>`抵挡全部 5 波，城堡还剩 ${state.hp} 点生命，击败 ${state.kills} 只小怪。`
 };
 $('#resultTag').textContent=won?'A LITTLE WORLD, A BIG ACHIEVEMENT':'ONE MORE LITTLE ADVENTURE';
 $('#resultTitle').textContent=won?titles[game.id]:'这一次，差一点点';
 $('#resultText').textContent=won?copies[game.id]():game.id==='puzzle'?`本局 ${state.score} 分。下一局试着让同类拼图连在一起，并完成三个组合目标。`:game.id==='town'?'20 天过去了。下一局早点建立树林、农场和集市，再扩大住宅。':'下一局试着在拐角附近集中建塔，让小怪在射程里停留更久。';
 if(!$('#guide').open&&!$('#result').open)$('#result').showModal();
}
function restart(){state=createState(game.id);tool=game.tools[0]?.[0]||state.hand?.[0]||'forest';resultShown=false;paused=false;$('#pause').textContent='Ⅱ';$('#result').close();sync();save();toast('新的一局已经准备好。');}
$('#advance').addEventListener('click',()=>operate('advance'));document.querySelectorAll('[data-dest]').forEach(b=>b.addEventListener('click',()=>operate('destination',{value:b.dataset.dest})));$('#resetView').addEventListener('click',()=>world.reset());$('#restart').addEventListener('click',()=>{if(confirm('重新开始这款小游戏？当前进度会被替换。'))restart();});$('#again').addEventListener('click',restart);$('#viewResult').addEventListener('click',()=>$('#result').close());$('#help').addEventListener('click',()=>$('#guide').showModal());$('#closeGuide').addEventListener('click',()=>{$('#guide').close();if(state.status!=='playing')showResult();});$('#pause').addEventListener('click',()=>{paused=!paused;$('#pause').textContent=paused?'▶':'Ⅱ';$('#pause').title=paused?'恢复动画':'暂停动画';toast(paused?'已暂停':'已继续');});$('#speed').addEventListener('click',()=>{speed=speed===1?2:1;$('#speed').textContent=`${speed}×`;});$('#weather').addEventListener('click',()=>{const index=weatherOptions.findIndex(w=>w.id===state.weather);state.weather=weatherOptions[(index+1)%weatherOptions.length].id;sync();save();});
const music=createMusic();music.setVolume(.3);$('#music').addEventListener('click',async()=>{try{if(music.playing)await music.stop();else await music.start();$('#music').setAttribute('aria-pressed',String(music.playing));$('#music').setAttribute('aria-label',music.playing?'关闭音乐':'开启音乐');$('#music').title=music.playing?'关闭音乐':'开启音乐';toast(music.playing?'背景音乐已开启':'背景音乐已关闭');}catch(e){toast(e.message);}});
document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden)save();});window.addEventListener('pagehide',save);sync();if(!sessionStorage.getItem(`arcade-seen-${game.id}`)&&state.status==='playing'){$('#guide').showModal();sessionStorage.setItem(`arcade-seen-${game.id}`,'1');}
function frame(now){requestAnimationFrame(frame);let dt=Math.min(.06,(now-last)/1000);last=now;if(document.hidden)return;if(paused||$('#guide').open||$('#result').open)dt=0;dt*=speed;time+=dt;const changed=dt>0?tick(state,dt):false;if(changed){sync();save();}world.step(state,time,dt);world.draw();}requestAnimationFrame(frame);
