import * as THREE from './three.module.js';
import {makeModel} from './models.js';
import {byId} from './catalog.js';
import {createWeather} from './weather.js';
import {GRID,ROAD,neighbors,key,pointOnPath} from './games.js';
export const TILE=1.6,FLOOR=.35;
export function createWorld(container,{id,onCell,onHover,preview=false}={}){
 const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:preview});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;container.append(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#233650');const camera=new THREE.OrthographicCamera(-10,10,8,-8,.1,100);let azimuth=.64,elevation=.76,zoom=1;
 const hemi=new THREE.HemisphereLight('#f3fff5','#7c8899',1.1);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff1dc',2.2);sun.position.set(-6,12,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12});sun.shadow.bias=-.001;scene.add(sun);const fill=new THREE.DirectionalLight('#a9d6ec',.45);fill.position.set(8,6,-10);scene.add(fill);
 const groundMat=new THREE.MeshStandardMaterial({color:'#6cc6a7',roughness:1,flatShading:true,side:THREE.DoubleSide}),sideMat=new THREE.MeshStandardMaterial({color:'#987967',roughness:1,flatShading:true,side:THREE.DoubleSide});const wx=createWeather({scene,sun,hemi,fill,groundMat});
 const island=new THREE.Group(),placed=new THREE.Group(),moving=new THREE.Group(),details=new THREE.Group(),beams=new THREE.Group();scene.add(island,placed,moving,details,beams);
 const mats=new Map();function material(color){if(!mats.has(color))mats.set(color,new THREE.MeshStandardMaterial({color,roughness:.95,flatShading:true}));return mats.get(color);}
 function cube(g,w,h,d,color,x=0,y=0,z=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
 function sphere(g,r,color,x=0,y=0,z=0){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(r,0),material(color));m.position.set(x,y,z);m.castShadow=true;g.add(m);return m;}
 function clear(g){for(const c of [...g.children]){g.remove(c);c.traverse(o=>o.geometry?.dispose());}}
 function model(type,x,z,scale=.85){const m=makeModel(type);m.position.set(x*TILE,FLOOR+.018,z*TILE);m.scale.multiplyScalar(scale);placed.add(m);return m;}
 const top=[],sides=[],set=new Set(GRID.map(p=>key(...p)));for(const [cx,cz] of GRID){const x=cx*TILE,z=cz*TILE,h=TILE/2,a=[x-h,FLOOR,z-h],b=[x+h,FLOOR,z-h],c=[x+h,FLOOR,z+h],d=[x-h,FLOOR,z+h];top.push(...a,...c,...b,...a,...d,...c);const edges=[[[x-h,z-h],[x+h,z-h],0,-1],[[x+h,z-h],[x+h,z+h],1,0],[[x+h,z+h],[x-h,z+h],0,1],[[x-h,z+h],[x-h,z-h],-1,0]];for(const [a,b,dx,dz]of edges)if(!set.has(key(cx+dx,cz+dz)))sides.push(a[0],FLOOR,a[1],b[0],-.43,b[1],b[0],FLOOR,b[1],a[0],FLOOR,a[1],a[0],-.43,a[1],b[0],-.43,b[1]);}
 for(const [verts,mat]of [[top,groundMat],[sides,sideMat]]){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.computeVertexNormals();const m=new THREE.Mesh(geo,mat);m.receiveShadow=true;m.castShadow=true;island.add(m);}
 const gridVerts=[];for(const [cx,cz]of GRID){const x=cx*TILE,z=cz*TILE,h=TILE/2;gridVerts.push(x-h,FLOOR+.006,z-h,x+h,FLOOR+.006,z-h,x+h,FLOOR+.006,z-h,x+h,FLOOR+.006,z+h,x+h,FLOOR+.006,z+h,x-h,FLOOR+.006,z+h,x-h,FLOOR+.006,z+h,x-h,FLOOR+.006,z-h);}
 const gridGeo=new THREE.BufferGeometry();gridGeo.setAttribute('position',new THREE.Float32BufferAttribute(gridVerts,3));island.add(new THREE.LineSegments(gridGeo,new THREE.LineBasicMaterial({color:'#d1f1db',transparent:true,opacity:preview?0:.2})));
 if(id==='defense')for(const [x,z]of ROAD){cube(details,TILE,.023,TILE,'#c0ae8c',x*TILE,FLOOR+.013,z*TILE);for(const [dx,dz]of [[-.3,0],[.25,.32]])cube(details,.28,.008,.16,'#e0cda2',(x+dx)*TILE,FLOOR+.029,(z+dz)*TILE);}
 const hover=new THREE.Mesh(new THREE.PlaneGeometry(TILE*.94,TILE*.94),new THREE.MeshBasicMaterial({color:'#d3f5b3',transparent:true,opacity:.25,depthWrite:false,side:THREE.DoubleSide}));hover.rotation.x=-Math.PI/2;hover.visible=false;scene.add(hover);
 let signature='',state=null,weather='sunny';const enemyMeshes=new Map(),visitors=[],citizens=[];
 const train=new THREE.Group();cube(train,.56,.35,.92,'#668daf',0,.32,0);cube(train,.4,.43,.4,'#d4e4cf',0,.48,-.17);cube(train,.35,.09,.47,'#42627d',0,.74,-.17);cube(train,.15,.25,.15,'#3e5a6e',0,.65,.27);for(const x of [-.28,.28])for(const z of [-.26,.26])sphere(train,.12,'#43536a',x,.15,z);cube(train,.5,.18,.65,'#c19a69',0,.27,-1);cube(train,.36,.24,.43,'#e2c596',0,.44,-1);for(const x of [-.26,.26])for(const z of [-.79,-1.21])sphere(train,.1,'#43536a',x,.12,z);train.visible=id==='train';moving.add(train);
 if(id==='town')for(let i=0;i<8;i++){const c=new THREE.Group();cube(c,.12,.2,.12,['#e6b48b','#97b5d5','#d4a6c2'][i%3],0,.2,0);sphere(c,.09,'#efd6af',0,.39,0);citizens.push(c);moving.add(c);}
 function rebuild(s){state=s;const sig=JSON.stringify(s.items)+JSON.stringify(s.visitors||[]);if(s.weather!==weather){weather=s.weather;wx.set(weather);}if(sig===signature)return;signature=sig;clear(placed);
  for(const i of s.items){
   if(i.type==='rail'){
    const g=new THREE.Group();g.position.set(i.x*TILE,FLOOR+.03,i.z*TILE);placed.add(g);const linked=neighbors(i.x,i.z).filter(([x,z])=>s.items.some(n=>n.x===x&&n.z===z&&(n.type==='rail'||n.station)));for(const [x,z]of linked){const dx=x-i.x,dz=z-i.z;for(const off of [-.18,.18])cube(g,dx?.85:.035,.035,dz?.85:.035,'#536575',dx*.39+(dz?off:0),.035,dz*.39+(dx?off:0));}for(const n of [-.45,0,.45])cube(g,.69,.028,.1,'#cda173',0,.018,n);if(!linked.length)for(const x of [-.18,.18])cube(g,.035,.035,1.1,'#536575',x,.035,0);continue;
   }
   const m=model(i.type==='ballista'?'smithy':i.type,i.x,i.z);m.userData.item=i;
   if(id==='garden'&&i.age!==undefined){const scale=.28+.72*Math.min(1,i.age/(i.type==='cherry'?3:2));m.scale.multiplyScalar(Math.min(1,scale));if(i.wet){const drop=new THREE.Mesh(new THREE.IcosahedronGeometry(.075,0),material('#85d8f0'));drop.position.set(i.x*TILE+.46,FLOOR+.14,i.z*TILE+.46);placed.add(drop);}}
   if(id==='puzzle'){const colors={forest:'#62ae82',pond:'#78c9cb',cottage:'#cbd1a1',flowers:'#dab4be',hill:'#8bc49b'};const patch=new THREE.Mesh(new THREE.PlaneGeometry(TILE*.97,TILE*.97),material(colors[i.type]));patch.rotation.x=-Math.PI/2;patch.position.set(i.x*TILE,FLOOR+.012,i.z*TILE);placed.add(patch);}
   if(id==='defense'&&!i.fixed){const range={watchtower:2.4,roundtower:2.2,ballista:3.2}[i.type];const ring=new THREE.Mesh(new THREE.RingGeometry(range*TILE-.012,range*TILE,64),new THREE.MeshBasicMaterial({color:i.type==='roundtower'?'#a5dced':'#e6d4b0',transparent:true,opacity:.13,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.set(i.x*TILE,FLOOR+.036,i.z*TILE);placed.add(ring);if(i.type==='ballista'){cube(m,.62,.09,.11,'#654e43',0,.53,.34);cube(m,.09,.12,.65,'#a3815c',0,.59,.34);}}
  }
  if(id==='train')for(const i of s.items.filter(i=>i.station)){for(const x of [-.2,.2])cube(placed,.036,.024,TILE,'#556879',i.x*TILE+x,FLOOR+.033,i.z*TILE);}
  if(id==='garden'){visitors.forEach(v=>{moving.remove(v);v.traverse(o=>o.geometry?.dispose());});visitors.length=0;for(let n=0;n<s.visitors.length;n++){const b=new THREE.Group();sphere(b,.07,'#ede7b3');const color=['#e8a4c6','#e6c472','#9cc6e9','#b6e4a1'][n];const wings=[];for(const sign of [-1,1]){const w=sphere(b,.14,color,sign*.13,0,0);w.scale.set(1,.15,.8);wings.push(w);}b.userData.wings=wings;visitors.push(b);moving.add(b);}}
 }
 function step(s,time,dt){wx.update(time,dt);placed.children.forEach(g=>{if(g.userData.rotor)g.userData.rotor.rotation.z=time*.7;});citizens.forEach((c,i)=>{c.visible=i<(s.items.filter(n=>n.type==='cottage').length*2);const a=time*.18+i*.9;c.position.set(Math.sin(a)*(2+i%2)*TILE,FLOOR,Math.cos(a)*1.15*TILE);c.rotation.y=a;});visitors.forEach((b,i)=>{b.position.set(Math.sin(time*.7+i*2)*3,FLOOR+1.25+Math.sin(time+i)*.35,Math.cos(time*.6+i*2)*2);b.rotation.y=-time*.7;for(const w of b.userData.wings)w.rotation.z=Math.sin(time*12)*.6;});
  if(id==='train'){const path=s.running?.path||[[-3,0],[-3,1]],p=s.running?.progress||0,[x,z]=pointOnPath(path,p);train.position.set(x*TILE,FLOOR+.028,z*TILE);const next=path[Math.min(path.length-1,Math.floor(p)+1)],prev=path[Math.min(path.length-2,Math.floor(p))];train.rotation.y=Math.atan2(next[0]-prev[0],next[1]-prev[1]);}
  if(id==='defense'){
   const ids=new Set(s.enemies.map(e=>e.id));for(const [eid,g]of enemyMeshes)if(!ids.has(eid)){moving.remove(g);g.traverse(o=>o.geometry?.dispose());enemyMeshes.delete(eid);}
   for(const e of s.enemies){let g=enemyMeshes.get(e.id);if(!g){g=new THREE.Group();const body=sphere(g,.25,'#d689a0',0,.26,0);body.scale.y=1.25;for(const x of [-.09,.09])sphere(g,.036,'#403d57',x,.33,.22);const health=cube(g,.46,.038,.05,'#bfe0a3',0,.71,0);g.userData.health=health;moving.add(g);enemyMeshes.set(e.id,g);}const [x,z]=pointOnPath(ROAD,e.progress);g.position.set(x*TILE,FLOOR+Math.sin(time*8+e.id)*.045,z*TILE);g.userData.health.scale.x=Math.max(.01,e.hp/e.max);}
   clear(beams);for(const shot of s.shots){const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(shot.x*TILE,FLOOR+1,shot.z*TILE),new THREE.Vector3(shot.to[0]*TILE,FLOOR+.4,shot.to[1]*TILE)]);beams.add(new THREE.Line(geo,new THREE.LineBasicMaterial({color:shot.type==='roundtower'?'#b6efff':'#f2d887'})));}
  }
 }
 function updateCamera(){const d=20;camera.position.set(Math.sin(azimuth)*Math.cos(elevation)*d,Math.sin(elevation)*d,Math.cos(azimuth)*Math.cos(elevation)*d);camera.lookAt(0,.35,0);camera.updateMatrixWorld();}
 function resize(){const w=container.clientWidth||540,h=container.clientHeight||300;renderer.setSize(w,h,false);const aspect=w/h,view=Math.max(4.8,7.4/aspect)/zoom;camera.left=-view*aspect;camera.right=view*aspect;camera.top=view;camera.bottom=-view;camera.updateProjectionMatrix();updateCamera();}
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),-FLOOR),point=new THREE.Vector3();function cell(e){const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);if(!ray.ray.intersectPlane(plane,point))return null;const x=Math.round(point.x/TILE),z=Math.round(point.z/TILE);return set.has(key(x,z))?{x,z}:null;}
 const pointers=new Map();let start=null,moved=false,pinch=0;if(!preview){renderer.domElement.addEventListener('pointerdown',e=>{renderer.domElement.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){start={x:e.clientX,y:e.clientY};moved=false;}else{moved=true;start=null;const a=[...pointers.values()];pinch=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);}});renderer.domElement.addEventListener('pointermove',e=>{const p=cell(e);hover.visible=!!p;if(p){hover.position.set(p.x*TILE,FLOOR+.055,p.z*TILE);onHover?.(p,e,state?.items.find(i=>i.x===p.x&&i.z===p.z));}else onHover?.(null,e);if(!pointers.has(e.pointerId))return;const prev=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinch){zoom=Math.max(.7,Math.min(1.8,zoom*d/pinch));resize();}pinch=d;return;}if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>6)moved=true;if(moved){azimuth-=(e.clientX-prev.x)*.008;elevation=Math.max(.35,Math.min(1.2,elevation+(e.clientY-prev.y)*.006));updateCamera();}});renderer.domElement.addEventListener('pointerup',e=>{const single=pointers.size===1;pointers.delete(e.pointerId);if(single&&!moved&&start){const p=cell(e);if(p)onCell?.(p);}start=null;pinch=0;});renderer.domElement.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);start=null;pinch=0;});renderer.domElement.addEventListener('pointerleave',()=>{hover.visible=false;onHover?.(null,{});});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.7,Math.min(1.8,zoom*(e.deltaY>0?.92:1.08)));resize();},{passive:false});}
 const observer=new ResizeObserver(resize);observer.observe(container);resize();
 return {scene,camera,renderer,rebuild,step,resize,draw(){renderer.render(scene,camera);},reset(){azimuth=.64;elevation=.76;zoom=1;resize();},dispose(){observer.disconnect();scene.traverse(o=>{o.geometry?.dispose();});renderer.dispose();renderer.domElement.remove();},screenshot(){renderer.render(scene,camera);return renderer.domElement.toDataURL('image/png');}};
}
